import type { Product } from "./types"

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "Classic Cotton T-Shirt",
    price: 29.99,
    originalPrice: 39.99,
    category: "Tops",
    subcategory: "T-Shirts",
    image: "/white-cotton-t-shirt-on-model.jpg",
    images: ["/white-cotton-t-shirt-front-view.jpg", "/white-cotton-t-shirt-back-view.jpg"],
    description: "Comfortable and versatile cotton t-shirt perfect for everyday wear.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Navy", "Gray"],
    inStock: true,
    rating: 4.5,
    reviewCount: 128,
    tags: ["casual", "basic", "cotton"],
    brand: "StyleCo",
    createdAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Slim Fit Jeans",
    price: 79.99,
    category: "Bottoms",
    subcategory: "Jeans",
    image: "/dark-blue-slim-fit-jeans-on-model.jpg",
    images: ["/dark-blue-jeans-front-view.jpg", "/dark-blue-jeans-side-view.jpg"],
    description: "Modern slim fit jeans with stretch comfort and classic styling.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Dark Blue", "Light Blue", "Black"],
    inStock: true,
    rating: 4.3,
    reviewCount: 89,
    tags: ["denim", "slim-fit", "casual"],
    brand: "DenimCraft",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "3",
    name: "Floral Summer Dress",
    price: 89.99,
    originalPrice: 119.99,
    category: "Dresses",
    subcategory: "Summer Dresses",
    image: "/floral-summer-dress-model.png",
    images: ["/placeholder-tjrin.png", "/placeholder-vuotd.png"],
    description: "Light and airy summer dress with beautiful floral print.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Blue", "Floral Pink", "Floral Yellow"],
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
    tags: ["summer", "floral", "feminine"],
    brand: "FloralFashion",
    createdAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "4",
    name: "Leather Jacket",
    price: 199.99,
    category: "Outerwear",
    subcategory: "Jackets",
    image: "/placeholder-r4726.png",
    images: ["/placeholder-qrwa2.png", "/leather-jacket-back.png"],
    description: "Premium leather jacket with classic biker styling.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Brown"],
    inStock: false,
    rating: 4.8,
    reviewCount: 67,
    tags: ["leather", "biker", "premium"],
    brand: "LeatherLux",
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "5",
    name: "Casual Sneakers",
    price: 69.99,
    category: "Shoes",
    subcategory: "Sneakers",
    image: "/white-casual-sneakers.jpg",
    images: ["/white-sneakers-side-view.jpg", "/placeholder-l76i6.png"],
    description: "Comfortable casual sneakers perfect for everyday activities.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Gray"],
    inStock: true,
    rating: 4.4,
    reviewCount: 203,
    tags: ["casual", "comfortable", "everyday"],
    brand: "ComfortStep",
    createdAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "6",
    name: "Wool Sweater",
    price: 119.99,
    category: "Tops",
    subcategory: "Sweaters",
    image: "/placeholder-fss5m.png",
    images: ["/placeholder-4u0pp.png", "/placeholder-e3lk6.png"],
    description: "Cozy wool sweater perfect for cooler weather.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Navy", "Cream", "Burgundy"],
    inStock: true,
    rating: 4.6,
    reviewCount: 94,
    tags: ["wool", "warm", "cozy"],
    brand: "WoolCraft",
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "7",
    name: "Athletic Shorts",
    price: 34.99,
    category: "Bottoms",
    subcategory: "Shorts",
    image: "/placeholder-3usq5.png",
    images: ["/placeholder-nubda.png", "/placeholder-1giu5.png"],
    description: "Lightweight athletic shorts with moisture-wicking technology.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy", "Gray", "Red"],
    inStock: true,
    rating: 4.2,
    reviewCount: 145,
    tags: ["athletic", "moisture-wicking", "lightweight"],
    brand: "ActiveWear",
    createdAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "8",
    name: "Silk Blouse",
    price: 149.99,
    originalPrice: 199.99,
    category: "Tops",
    subcategory: "Blouses",
    image: "/placeholder.svg?height=400&width=300",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Elegant silk blouse perfect for professional or formal occasions.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Cream", "Black", "Blush"],
    inStock: true,
    rating: 4.9,
    reviewCount: 78,
    tags: ["silk", "elegant", "professional"],
    brand: "SilkStyle",
    createdAt: "2024-01-22T00:00:00Z",
  },
  {
    id: "9",
    name: "Denim Jacket",
    price: 89.99,
    category: "Outerwear",
    subcategory: "Jackets",
    image: "/classic-denim-jacket.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Classic denim jacket with vintage wash and modern fit.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    inStock: true,
    rating: 4.4,
    reviewCount: 112,
    tags: ["denim", "casual", "vintage"],
    brand: "DenimCraft",
    createdAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "10",
    name: "Maxi Dress",
    price: 129.99,
    originalPrice: 159.99,
    category: "Dresses",
    subcategory: "Maxi Dresses",
    image: "/elegant-maxi-dress.jpg",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Flowing maxi dress perfect for special occasions and evening events.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Burgundy", "Black", "Emerald"],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    tags: ["maxi", "elegant", "evening"],
    brand: "ElegantWear",
    createdAt: "2024-01-28T00:00:00Z",
  },
  {
    id: "11",
    name: "Running Shoes",
    price: 129.99,
    category: "Shoes",
    subcategory: "Athletic",
    image: "/running-shoes-on-track.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "High-performance running shoes with advanced cushioning technology.",
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Blue", "Red"],
    inStock: true,
    rating: 4.6,
    reviewCount: 234,
    tags: ["running", "athletic", "performance"],
    brand: "SportTech",
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "12",
    name: "Chino Pants",
    price: 59.99,
    category: "Bottoms",
    subcategory: "Chinos",
    image: "/chino-pants.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Versatile chino pants suitable for both casual and semi-formal occasions.",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "Olive"],
    inStock: true,
    rating: 4.3,
    reviewCount: 167,
    tags: ["chino", "versatile", "casual"],
    brand: "ClassicFit",
    createdAt: "2024-02-03T00:00:00Z",
  },
  {
    id: "13",
    name: "Cardigan Sweater",
    price: 79.99,
    category: "Tops",
    subcategory: "Cardigans",
    image: "/placeholder-qeke0.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Soft knit cardigan perfect for layering in any season.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Gray", "Navy", "Camel"],
    inStock: true,
    rating: 4.5,
    reviewCount: 98,
    tags: ["cardigan", "layering", "soft"],
    brand: "CozyKnits",
    createdAt: "2024-02-05T00:00:00Z",
  },
  {
    id: "14",
    name: "Cocktail Dress",
    price: 179.99,
    originalPrice: 229.99,
    category: "Dresses",
    subcategory: "Cocktail Dresses",
    image: "/elegant-cocktail-dress.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Sophisticated cocktail dress perfect for parties and formal events.",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Navy", "Burgundy", "Emerald"],
    inStock: false,
    rating: 4.8,
    reviewCount: 56,
    tags: ["cocktail", "formal", "sophisticated"],
    brand: "ElegantWear",
    createdAt: "2024-02-08T00:00:00Z",
  },
  {
    id: "15",
    name: "Polo Shirt",
    price: 49.99,
    category: "Tops",
    subcategory: "Polo Shirts",
    image: "/classic-polo-shirt.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Classic polo shirt with premium cotton blend and modern fit.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Navy", "Black", "Red", "Green"],
    inStock: true,
    rating: 4.4,
    reviewCount: 189,
    tags: ["polo", "classic", "cotton"],
    brand: "StyleCo",
    createdAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "16",
    name: "Ankle Boots",
    price: 149.99,
    category: "Shoes",
    subcategory: "Boots",
    image: "/stylish-ankle-boots.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Stylish ankle boots with comfortable heel and premium leather construction.",
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Black", "Brown", "Tan"],
    inStock: true,
    rating: 4.6,
    reviewCount: 134,
    tags: ["boots", "leather", "stylish"],
    brand: "FootwearPlus",
    createdAt: "2024-02-12T00:00:00Z",
  },
  {
    id: "17",
    name: "Hoodie",
    price: 69.99,
    category: "Tops",
    subcategory: "Hoodies",
    image: "/cozy-hoodie.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Comfortable cotton blend hoodie perfect for casual wear and lounging.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Gray", "Black", "Navy", "White"],
    inStock: true,
    rating: 4.3,
    reviewCount: 276,
    tags: ["hoodie", "casual", "comfortable"],
    brand: "ComfortWear",
    createdAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "18",
    name: "Midi Skirt",
    price: 64.99,
    category: "Bottoms",
    subcategory: "Skirts",
    image: "/midi-skirt.jpg",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Versatile midi skirt that transitions perfectly from day to night.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Camel", "Burgundy"],
    inStock: true,
    rating: 4.5,
    reviewCount: 123,
    tags: ["midi", "versatile", "day-to-night"],
    brand: "ModernStyle",
    createdAt: "2024-02-18T00:00:00Z",
  },
  {
    id: "19",
    name: "Blazer",
    price: 159.99,
    originalPrice: 199.99,
    category: "Outerwear",
    subcategory: "Blazers",
    image: "/placeholder-iptk0.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Tailored blazer perfect for professional settings and smart casual occasions.",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray", "Camel"],
    inStock: true,
    rating: 4.7,
    reviewCount: 87,
    tags: ["blazer", "professional", "tailored"],
    brand: "ProfessionalWear",
    createdAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "20",
    name: "Sandals",
    price: 79.99,
    category: "Shoes",
    subcategory: "Sandals",
    image: "/comfortable-sandals.png",
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    description: "Comfortable summer sandals with cushioned footbed and adjustable straps.",
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["Tan", "Black", "White", "Brown"],
    inStock: true,
    rating: 4.2,
    reviewCount: 198,
    tags: ["sandals", "summer", "comfortable"],
    brand: "SummerStep",
    createdAt: "2024-02-22T00:00:00Z",
  },
]

export const categories = ["Tops", "Bottoms", "Dresses", "Outerwear", "Shoes"]

export const subcategories = [
  "T-Shirts",
  "Jeans",
  "Summer Dresses",
  "Jackets",
  "Sneakers",
  "Sweaters",
  "Shorts",
  "Blouses",
  "Maxi Dresses",
  "Athletic",
  "Chinos",
  "Cardigans",
  "Cocktail Dresses",
  "Polo Shirts",
  "Boots",
  "Hoodies",
  "Skirts",
  "Blazers",
  "Sandals",
]

export const brands = [
  "StyleCo",
  "DenimCraft",
  "FloralFashion",
  "LeatherLux",
  "ComfortStep",
  "WoolCraft",
  "ActiveWear",
  "SilkStyle",
  "ElegantWear",
  "SportTech",
  "ClassicFit",
  "CozyKnits",
  "FootwearPlus",
  "ComfortWear",
  "ModernStyle",
  "ProfessionalWear",
  "SummerStep",
]

export const sizes = [
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "28",
  "30",
  "32",
  "34",
  "36",
  "38",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
]

export const colors = [
  "White",
  "Black",
  "Navy",
  "Gray",
  "Dark Blue",
  "Light Blue",
  "Floral Blue",
  "Floral Pink",
  "Floral Yellow",
  "Brown",
  "Cream",
  "Burgundy",
  "Red",
  "Blush",
  "Khaki",
  "Olive",
  "Camel",
  "Emerald",
  "Green",
  "Tan",
]
